//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyBank.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyBank.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        public static string AccountId_lb {
            get {
                return ResourceManager.GetString("AccountId_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber_lb {
            get {
                return ResourceManager.GetString("AccountNumber_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions_lb {
            get {
                return ResourceManager.GetString("Actions_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount_lb {
            get {
                return ResourceManager.GetString("Amount_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure You want to delete that account?.
        /// </summary>
        public static string AreYouSure_lb {
            get {
                return ResourceManager.GetString("AreYouSure_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Back_btn {
            get {
                return ResourceManager.GetString("Back_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance_lb {
            get {
                return ResourceManager.GetString("Balance_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the currency.
        /// </summary>
        public static string ChooseCurrency_lb {
            get {
                return ResourceManager.GetString("ChooseCurrency_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an account ID.
        /// </summary>
        public static string ChooseId_lb {
            get {
                return ResourceManager.GetString("ChooseId_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose target currency.
        /// </summary>
        public static string ChooseTargetCurrency_lb {
            get {
                return ResourceManager.GetString("ChooseTargetCurrency_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your currency.
        /// </summary>
        public static string ChooseYourCurrency_lb {
            get {
                return ResourceManager.GetString("ChooseYourCurrency_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Account.
        /// </summary>
        public static string CreateYourAccount_lb {
            get {
                return ResourceManager.GetString("CreateYourAccount_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency_lb {
            get {
                return ResourceManager.GetString("Currency_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_btn {
            get {
                return ResourceManager.GetString("Delete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete An Account.
        /// </summary>
        public static string DeleteAnAcc_lb {
            get {
                return ResourceManager.GetString("DeleteAnAcc_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an account.
        /// </summary>
        public static string DeleteAnAccount_btn {
            get {
                return ResourceManager.GetString("DeleteAnAccount_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit_btn {
            get {
                return ResourceManager.GetString("Deposit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit_lb {
            get {
                return ResourceManager.GetString("Deposit_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit the currency.
        /// </summary>
        public static string DepositTheCurrency_btn {
            get {
                return ResourceManager.GetString("DepositTheCurrency_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination account number.
        /// </summary>
        public static string DestinationAccNr_lb {
            get {
                return ResourceManager.GetString("DestinationAccNr_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_lb {
            get {
                return ResourceManager.GetString("Email_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Exchange_btn {
            get {
                return ResourceManager.GetString("Exchange_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Exchange_btn1 {
            get {
                return ResourceManager.GetString("Exchange_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange the Currency.
        /// </summary>
        public static string ExchangeTheCurrency_lb {
            get {
                return ResourceManager.GetString("ExchangeTheCurrency_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Firstname_lb {
            get {
                return ResourceManager.GetString("Firstname_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From_lb {
            get {
                return ResourceManager.GetString("From_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Lastname_lb {
            get {
                return ResourceManager.GetString("Lastname_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string LoggedInAs_lb {
            get {
                return ResourceManager.GetString("LoggedInAs_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_btn {
            get {
                return ResourceManager.GetString("Login_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_lb {
            get {
                return ResourceManager.GetString("Login_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Into Your Account.
        /// </summary>
        public static string LogIntoYourAccount_lb {
            get {
                return ResourceManager.GetString("LogIntoYourAccount_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff_btn {
            get {
                return ResourceManager.GetString("LogOff_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Accounts.
        /// </summary>
        public static string ManageYourAccounts_lb {
            get {
                return ResourceManager.GetString("ManageYourAccounts_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transfer.
        /// </summary>
        public static string NewTransfer_btn {
            get {
                return ResourceManager.GetString("NewTransfer_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Transfer.
        /// </summary>
        public static string NewTransfer_lb {
            get {
                return ResourceManager.GetString("NewTransfer_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open_btn {
            get {
                return ResourceManager.GetString("Open_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new account.
        /// </summary>
        public static string OpenANewAccount_btn {
            get {
                return ResourceManager.GetString("OpenANewAccount_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a New Account.
        /// </summary>
        public static string OpenANewAccount_lb {
            get {
                return ResourceManager.GetString("OpenANewAccount_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or  Register.
        /// </summary>
        public static string OrRegister_btn {
            get {
                return ResourceManager.GetString("OrRegister_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_lb {
            get {
                return ResourceManager.GetString("Password_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesel.
        /// </summary>
        public static string Pesel_lb {
            get {
                return ResourceManager.GetString("Pesel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_btn {
            get {
                return ResourceManager.GetString("Register_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_lb {
            get {
                return ResourceManager.GetString("Register_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer_btn {
            get {
                return ResourceManager.GetString("Transfer_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username_lb {
            get {
                return ResourceManager.GetString("Username_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw_btn {
            get {
                return ResourceManager.GetString("Withdraw_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        public static string Withdrawal_btn {
            get {
                return ResourceManager.GetString("Withdrawal_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        public static string Withdrawal_lb {
            get {
                return ResourceManager.GetString("Withdrawal_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accounts.
        /// </summary>
        public static string YourAccounts_lb {
            get {
                return ResourceManager.GetString("YourAccounts_lb", resourceCulture);
            }
        }
    }
}
